/* eslint-disable @typescript-eslint/no-use-before-define */

import ß from 'bhala'
import { app, BrowserWindow, ipcMain, Menu, nativeImage, screen, session, Tray } from 'electron'
import electronIsDev from 'electron-is-dev'
import { autoUpdater, ProgressInfo } from 'electron-updater'
import path from 'path'

import { Clamd } from './libs/Clamd'
import { FreshClam } from './libs/FreshClam'

import type { UpdateInfo } from 'electron-updater'

// Magic constants auto-generated by Forge's Webpack plugin
// https://www.electronforge.io/config/plugins/webpack#project-setup
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string
declare const MAIN_WINDOW_WEBPACK_ENTRY: string

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
// eslint-disable-next-line global-require
if (require('electron-squirrel-startup')) {
  app.quit()
}

let isHidden = false
let isQuitting = false
const isStarting = false
const isUpdating = false
let mainWindow: BrowserWindow
let tray: Tray

// Force single instance
if (!app.requestSingleInstanceLock()) {
  app.quit()
}

const createWindow = (): void => {
  const primaryDisplay = screen.getPrimaryDisplay()

  mainWindow = new BrowserWindow({
    fullscreenable: false,
    height: 384,
    movable: false,
    resizable: false,
    show: false,
    titleBarStyle: 'hidden',
    transparent: false,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
    width: 683,
  })

  mainWindow.setAlwaysOnTop(true)
  mainWindow.setPosition(primaryDisplay.workAreaSize.width - 683 - 20, primaryDisplay.workAreaSize.height - 384 - 20)
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY)

  mainWindow.once('ready-to-show', async () => {
    if (electronIsDev) {
      mainWindow.setResizable(true)
      mainWindow.maximize()
      mainWindow.webContents.openDevTools()
      // mainWindow.show()
    }
  })

  mainWindow.on('close', (event: Event) => {
    if (isQuitting) {
      return
    }

    event.preventDefault()
    toggleMainWindows()
  })
}

app.once('ready', async () => {
  if (!electronIsDev) {
    session.defaultSession.webRequest.onHeadersReceived((details, callback) => {
      callback({
        responseHeaders: {
          ...details.responseHeaders,
          'Content-Security-Policy': [
            ["default-src 'none'", 'font-src data:', "script-src-elem 'self'", "style-src 'unsafe-inline'"].join('; '),
          ],
        },
      })
    })
  }

  const clamd = new Clamd()
  const freshClam = new FreshClam()

  ipcMain.handle('clamd:isRunning', clamd.isRunning)
  ipcMain.handle('clamd:start', clamd.start)
  ipcMain.handle('clamd:stop', clamd.stop)

  ipcMain.handle('freshClam:run', freshClam.run)
  ipcMain.handle('freshClam:isRunning', freshClam.isRunning)

  createWindow()

  app.on('activate', () => {
    // On OS X it's common to re-create a window in the app when the
    // dock icon is clicked and there are no other windows open.
    if (BrowserWindow.getAllWindows().length === 0) {
      createWindow()
    }
  })

  const icon = nativeImage.createFromPath(path.join(__dirname, '../assets/icons/logo-clamav.ico'))
  tray = new Tray(icon)
  tray.setToolTip('ClamAV Desktop')
  tray.on('click', toggleMainWindows)
  updateTray()
})

app.on('second-instance', () => {
  // Someone tried to run a second instance, we should focus our window.
  if (mainWindow) {
    if (mainWindow.isMinimized()) {
      mainWindow.restore()
    }
    mainWindow.focus()
  }
})

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

// autoUpdater.on('checking-for-update', () => {
//   mainWindow.webContents.send('ipcMain:autoUpdater:checking')
// })
autoUpdater.on('update-available', (info: UpdateInfo) => {
  mainWindow.webContents.send('ipcMain:autoUpdater:found', JSON.stringify(info))
})
/* autoUpdater.on('update-not-available', (info: any) => {
  mainWindow.webContents.send('ipcMain:autoUpdater:notFound', JSON.stringify(info))
})
autoUpdater.on('error', (err: any) => {
  mainWindow.webContents.send('ipcMain:autoUpdater:error', JSON.stringify(err))
}) */
autoUpdater.on('download-progress', (progressObj: ProgressInfo) => {
  mainWindow.webContents.send('ipcMain:autoUpdater:progress', JSON.stringify(progressObj))
})
autoUpdater.on('update-downloaded', (info: any) => {
  mainWindow.webContents.send('ipcMain:autoUpdater:downloaded', JSON.stringify(info))
})

async function exitApp(toInstallUpdate = false): Promise<void> {
  if (isStarting || (isUpdating && !toInstallUpdate)) {
    return
  }
  isQuitting = true

  try {
    mainWindow.webContents.send('ipcMain:app:quit')

    const clamd = new Clamd()
    await clamd.stop()
  } catch (err) {
    ß.error(err)

    if (toInstallUpdate) {
      autoUpdater.quitAndInstall()
    } else {
      app.quit()
    }
  }

  if (toInstallUpdate) {
    autoUpdater.quitAndInstall()
  } else {
    app.quit()
  }
}

function toggleMainWindows(): void {
  if (isHidden) {
    mainWindow.show()
    isHidden = false
    updateTray()

    return
  }

  mainWindow.hide()
  isHidden = true
  updateTray()
}

function updateTray(): void {
  const contextMenu: Menu = Menu.buildFromTemplate(
    (isHidden
      ? [
          {
            click: toggleMainWindows,
            label: 'Show ClamAV Desktop',
          },
        ]
      : [
          {
            click: toggleMainWindows,
            label: 'Minimize to Tray',
          },
        ]
    ).concat([
      {
        click: () => exitApp(false),
        label: 'Exit',
      },
    ]),
  )

  tray.setContextMenu(contextMenu)
}
