[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.0.0"
common = { path = "../common" }
tokio = { version = "1.34.0", features = ["full"] }

[dev-dependencies]
dev = { path = "../dev" }
jrest = "0.2.3"
