# https://github.com/cawa-93/vite-electron-builder/blob/main/.github/actions/release-notes/main.js

name: "Release Notes"
description: "Return release notes based on Git Commits"
inputs:
  from:
    description: "Commit from which start log"
    required: true
  to:
    description: "Commit to which end log"
    required: true
  include-commit-body:
    description: "Should the commit body be in notes"
    required: false
    default: "false"
  include-abbreviated-commit:
    description: "Should the commit sha be in notes"
    required: false
    default: "true"
outputs:
  release-note: # id of output
    description: "Release notes"
runs:
  using: "node16"
  main: "main.js"
