[package]
name = "dev"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]

[dev-dependencies]
jrest = "0.2.3"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tarpaulin_include)'] }
