[package]
name = "filer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cli = { path = "../cli" }
common = { path = "../common" }
# TODO Replace that with the v0.3.2 once it's released.
# This release will include https://github.com/rust-lang/glob/pull/112 is released.
glob = { path = "../glob" }
serde = { version = "1.0.164", features = ["derive"] }

[dev-dependencies]
dev = { path = "../dev" }
jrest = "0.2.3"
