[package]
name = "filer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cli = { path = "../cli" }
common = { path = "../common" }
glob = "0.3.1"
jest = { path = "../jest" }
serde = { version = "1.0.154", features = ["derive"] }
serde_test = "1.0.154"
