name: Integration

on: push

jobs:
  e2e_debian:
    name: E2E (debian-latest)
    runs-on: ubuntu-latest
    container:
      image: ivangabriele/tauri:debian-bullseye-18
    env:
      DISABLE_ESLINT_PLUGIN: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      # https://github.com/Swatinem/rust-cache#example-usage
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          key: integration_e2e_debian-latest
          prefix-key: rust-cache
          shared-key: v0
          workspaces: './src-tauri -> target'
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 20
      - name: Install ClamAV
        run: |
          apt-get update
          apt-get install -y clamav
      - name: Print ClamAV version
        run: clamscan -V
      - name: Install Node.js dependencies
        run: yarn --frozen-lockfile
      - name: Run tests
        uses: nick-fields/retry@v2
        with:
          timeout_seconds: 600
          max_attempts: 3
          retry_on: error
          command: |
            fuser -n tcp -k 4445
            yarn test:e2e
