name: Integration

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

concurrency:
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  e2e_debian:
    name: E2E (debian-latest)
    runs-on: ubuntu-latest
    container:
      image: ivangabriele/tauri:debian-bullseye-18
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false
      # https://github.com/Swatinem/rust-cache#example-usage
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          key: integration_e2e_debian-latest
          prefix-key: rust-cache
          shared-key: v0
          workspaces: './src-tauri -> target'
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: yarn
          node-version: 22
      - name: Install Debian dependencies
        run: |
          apt-get update
          apt-get install -y dbus-x11
      - name: Install ClamAV
        run: |
          apt-get install -y clamav
      - name: Print ClamAV version
        run: clamscan -V
      - name: Install Node.js dependencies
        run: yarn --frozen-lockfile
      - name: Build binary
        run: yarn bundle:bin
      - name: Run tests
        uses: nick-fields/retry@v3
        with:
          timeout_seconds: 600
          max_attempts: 3
          retry_on: error
          command: |
            fuser -n tcp -k 4445
            yarn test:e2e
